name: toml-reader
version: 0.1.0.0
synopsis: TOML format parser compliant with v1.0.0.
description: See README.md
license: BSD3
author: Brandon Chinn <brandonchinn178@gmail.com>
maintainer: Brandon Chinn <brandonchinn178@gmail.com>

extra-source-files:
  - README.md

github: brandonchinn178/toml-reader

ghc-options: -Wall
when:
  - condition: impl(ghc >= 8.0)
    ghc-options:
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wnoncanonical-monad-instances

library:
  source-dirs: src
  dependencies:
    - base >= 4.9 && < 5
    - containers >= 0.6.0.1 && < 0.7
    - deepseq >= 1.4.4.0 && < 1.5
    - megaparsec >= 7.0.5 && < 9.3
    - parser-combinators >= 1.1.0 && < 1.4
    - text >= 1.2.3.1 && < 1.3
    - time >= 1.8.0.2 && < 1.12

tests:
  toml-reader-tests:
    main: Main.hs
    source-dirs: test/tasty
    dependencies:
      - base
      - containers
      - tasty
      - tasty-golden
      - tasty-hunit
      - text
      - time
      - toml-reader

  parser-validator:
    main: ValidateParser.hs
    source-dirs: test/toml-test
    dependencies:
      - aeson
      - base
      - bytestring
      - containers
      - directory
      - process
      - text
      - time
      - toml-reader
      - unordered-containers
      - vector
