name: toml-reader
version: 0.1.0.0
synopsis: TOML format parser compliant with v1.0.0.
description: See README.md
license: BSD3
author: Brandon Chinn <brandonchinn178@gmail.com>
maintainer: Brandon Chinn <brandonchinn178@gmail.com>

extra-source-files:
  - README.md

github: brandonchinn178/toml-reader

ghc-options: -Wall
when:
  - condition: impl(ghc >= 8.0)
    ghc-options:
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wnoncanonical-monad-instances
  - condition: impl(ghc < 8.8)
    ghc-options:
      - -Wnoncanonical-monadfail-instances

library:
  source-dirs: src
  dependencies:
    - base >= 4.9 && < 5
    - text >= 1.2.3.1 && < 1.3

tests:
  toml-validator:
    main: Validate.hs
    source-dirs: test
    dependencies:
      - base
      - text
