name: CI
on: push

jobs:
  build_and_test:
    strategy:
      matrix:
        stack_yaml:
          - stack-ghc-8.6.yaml
          - stack-ghc-8.8.yaml
          - stack-ghc-8.10.yaml
          - stack-ghc-9.0.yaml
          - stack-ghc-9.2.yaml
        include:
          - stack_yaml: stack.yaml
            latest: true

    name: build_and_test (${{ matrix.stack_yaml }})
    runs-on: ubuntu-latest
    env:
      STACK_YAML: ${{ matrix.stack_yaml }}

    steps:
      - uses: actions/checkout@v2

      - name: Install toml-test
        env:
          TOML_TEST_VERSION: '1.1.0'
        run: |
          curl -sSL \
            "https://github.com/BurntSushi/toml-test/releases/download/v${TOML_TEST_VERSION}/toml-test-v${TOML_TEST_VERSION}-linux-amd64.gz" \
            -o toml-test.gz
          gunzip toml-test.gz
          chmod +x toml-test
          mv toml-test /usr/local/bin/

      - uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-cache-${{ hashFiles(matrix.stack_yaml, 'package.yaml') }}
      - name: Build + test
        run: |
          stack build --test --coverage --ta '
            -skip valid/array/array
            -skip valid/array/bool
            -skip valid/array/empty
            -skip valid/array/hetergeneous
            -skip valid/array/mixed-int-array
            -skip valid/array/mixed-int-float
            -skip valid/array/mixed-int-string
            -skip valid/array/mixed-string-table
            -skip valid/array/nested-double
            -skip valid/array/nested-inline-table
            -skip valid/array/nested
            -skip valid/array/nospaces
            -skip valid/array/string-quote-comma-2
            -skip valid/array/string-quote-comma
            -skip valid/array/string-with-comma
            -skip valid/array/strings
            -skip valid/array/table-array-string-backslash
            -skip valid/bool/bool
            -skip valid/comment/at-eof
            -skip valid/comment/at-eof2
            -skip valid/comment/everywhere
            -skip valid/comment/noeol
            -skip valid/comment/tricky
            -skip valid/datetime/datetime
            -skip valid/datetime/local-date
            -skip valid/datetime/local-time
            -skip valid/datetime/local
            -skip valid/datetime/milliseconds
            -skip valid/datetime/timezone
            -skip valid/empty-file
            -skip valid/example
            -skip valid/float/exponent
            -skip valid/float/float
            -skip valid/float/inf-and-nan
            -skip valid/float/long
            -skip valid/float/underscore
            -skip valid/float/zero
            -skip valid/implicit-and-explicit-after
            -skip valid/implicit-and-explicit-before
            -skip valid/implicit-groups
            -skip valid/inline-table/array
            -skip valid/inline-table/bool
            -skip valid/inline-table/empty
            -skip valid/inline-table/end-in-bool
            -skip valid/inline-table/inline-table
            -skip valid/inline-table/key-dotted
            -skip valid/inline-table/multiline
            -skip valid/inline-table/nest
            -skip valid/integer/integer
            -skip valid/integer/literals
            -skip valid/integer/long
            -skip valid/integer/underscore
            -skip valid/integer/zero
            -skip valid/key/alphanum
            -skip valid/key/case-sensitive
            -skip valid/key/dotted
            -skip valid/key/empty
            -skip valid/key/equals-nospace
            -skip valid/key/escapes
            -skip valid/key/numeric-dotted
            -skip valid/key/numeric
            -skip valid/key/quoted-dots
            -skip valid/key/space
            -skip valid/key/special-chars
            -skip valid/key/special-word
            -skip valid/newline-crlf
            -skip valid/newline-lf
            -skip valid/spec-example-1-compact
            -skip valid/spec-example-1
            -skip valid/string/double-quote-escape
            -skip valid/string/empty
            -skip valid/string/escape-tricky
            -skip valid/string/escaped-escape
            -skip valid/string/escapes
            -skip valid/string/multiline-escaped-crlf
            -skip valid/string/multiline-quotes
            -skip valid/string/multiline
            -skip valid/string/nl
            -skip valid/string/raw-multiline
            -skip valid/string/raw
            -skip valid/string/simple
            -skip valid/string/unicode-escape
            -skip valid/string/unicode-literal
            -skip valid/string/with-pound
            -skip valid/table/array-implicit
            -skip valid/table/array-many
            -skip valid/table/array-nest
            -skip valid/table/array-one
            -skip valid/table/array-table-array
            -skip valid/table/empty
            -skip valid/table/keyword
            -skip valid/table/names
            -skip valid/table/no-eol
            -skip valid/table/sub-empty
            -skip valid/table/whitespace
            -skip valid/table/with-literal-string
            -skip valid/table/with-pound
            -skip valid/table/with-single-quotes
            -skip valid/table/without-super
            -skip invalid/array/missing-separator
            -skip invalid/array/no-close-2
            -skip invalid/array/no-close-table-2
            -skip invalid/array/no-close-table
            -skip invalid/array/no-close
            -skip invalid/array/tables-1
            -skip invalid/array/tables-2
            -skip invalid/array/text-after-array-entries
            -skip invalid/array/text-before-array-separator
            -skip invalid/array/text-in-array
            -skip invalid/bool/mixed-case
            -skip invalid/bool/wrong-case-false
            -skip invalid/bool/wrong-case-true
            -skip invalid/control/bare-cr
            -skip invalid/control/bare-formfeed
            -skip invalid/control/bare-null
            -skip invalid/control/bare-vertical-tab
            -skip invalid/control/comment-cr
            -skip invalid/control/comment-del
            -skip invalid/control/comment-lf
            -skip invalid/control/comment-null
            -skip invalid/control/comment-us
            -skip invalid/control/multi-del
            -skip invalid/control/multi-lf
            -skip invalid/control/multi-null
            -skip invalid/control/multi-us
            -skip invalid/control/rawmulti-del
            -skip invalid/control/rawmulti-lf
            -skip invalid/control/rawmulti-null
            -skip invalid/control/rawmulti-us
            -skip invalid/control/rawstring-del
            -skip invalid/control/rawstring-lf
            -skip invalid/control/rawstring-null
            -skip invalid/control/rawstring-us
            -skip invalid/control/string-bs
            -skip invalid/control/string-del
            -skip invalid/control/string-lf
            -skip invalid/control/string-null
            -skip invalid/control/string-us
            -skip invalid/datetime/hour-over
            -skip invalid/datetime/mday-over
            -skip invalid/datetime/mday-under
            -skip invalid/datetime/minute-over
            -skip invalid/datetime/month-over
            -skip invalid/datetime/month-under
            -skip invalid/datetime/no-leads-with-milli
            -skip invalid/datetime/no-leads
            -skip invalid/datetime/no-secs
            -skip invalid/datetime/no-t
            -skip invalid/datetime/second-over
            -skip invalid/datetime/time-no-leads-2
            -skip invalid/datetime/time-no-leads
            -skip invalid/datetime/trailing-t
            -skip invalid/encoding/bad-utf8-at-end
            -skip invalid/encoding/bad-utf8-in-comment
            -skip invalid/encoding/bad-utf8-in-string
            -skip invalid/encoding/bom-not-at-start-1
            -skip invalid/encoding/bom-not-at-start-2
            -skip invalid/encoding/utf16-bom
            -skip invalid/encoding/utf16
            -skip invalid/float/double-point-1
            -skip invalid/float/double-point-2
            -skip invalid/float/exp-double-e-1
            -skip invalid/float/exp-double-e-2
            -skip invalid/float/exp-double-us
            -skip invalid/float/exp-leading-us
            -skip invalid/float/exp-point-1
            -skip invalid/float/exp-point-2
            -skip invalid/float/exp-trailing-us
            -skip invalid/float/inf-incomplete-1
            -skip invalid/float/inf-incomplete-2
            -skip invalid/float/inf-incomplete-3
            -skip invalid/float/inf_underscore
            -skip invalid/float/leading-point-neg
            -skip invalid/float/leading-point-plus
            -skip invalid/float/leading-point
            -skip invalid/float/leading-us
            -skip invalid/float/leading-zero-neg
            -skip invalid/float/leading-zero-plus
            -skip invalid/float/leading-zero
            -skip invalid/float/nan-incomplete-1
            -skip invalid/float/nan-incomplete-2
            -skip invalid/float/nan-incomplete-3
            -skip invalid/float/nan_underscore
            -skip invalid/float/trailing-point-min
            -skip invalid/float/trailing-point-plus
            -skip invalid/float/trailing-point
            -skip invalid/float/trailing-us-exp
            -skip invalid/float/trailing-us
            -skip invalid/float/us-after-point
            -skip invalid/float/us-before-point
            -skip invalid/inline-table/add
            -skip invalid/inline-table/double-comma
            -skip invalid/inline-table/duplicate-key
            -skip invalid/inline-table/empty
            -skip invalid/inline-table/linebreak-1
            -skip invalid/inline-table/linebreak-2
            -skip invalid/inline-table/linebreak-3
            -skip invalid/inline-table/linebreak-4
            -skip invalid/inline-table/no-comma
            -skip invalid/inline-table/overwrite
            -skip invalid/inline-table/trailing-comma
            -skip invalid/integer/capital-bin
            -skip invalid/integer/capital-hex
            -skip invalid/integer/capital-oct
            -skip invalid/integer/double-sign-nex
            -skip invalid/integer/double-sign-plus
            -skip invalid/integer/double-us
            -skip invalid/integer/incomplete-bin
            -skip invalid/integer/incomplete-hex
            -skip invalid/integer/incomplete-oct
            -skip invalid/integer/invalid-bin
            -skip invalid/integer/invalid-hex
            -skip invalid/integer/invalid-oct
            -skip invalid/integer/leading-us-bin
            -skip invalid/integer/leading-us-hex
            -skip invalid/integer/leading-us-oct
            -skip invalid/integer/leading-us
            -skip invalid/integer/leading-zero-1
            -skip invalid/integer/leading-zero-2
            -skip invalid/integer/leading-zero-3
            -skip invalid/integer/leading-zero-sign-1
            -skip invalid/integer/leading-zero-sign-2
            -skip invalid/integer/leading-zero-sign-3
            -skip invalid/integer/negative-bin
            -skip invalid/integer/negative-hex
            -skip invalid/integer/negative-oct
            -skip invalid/integer/positive-bin
            -skip invalid/integer/positive-hex
            -skip invalid/integer/positive-oct
            -skip invalid/integer/text-after-integer
            -skip invalid/integer/trailing-us-bin
            -skip invalid/integer/trailing-us-hex
            -skip invalid/integer/trailing-us-oct
            -skip invalid/integer/trailing-us
            -skip invalid/integer/us-after-bin
            -skip invalid/integer/us-after-hex
            -skip invalid/integer/us-after-oct
            -skip invalid/key/after-array
            -skip invalid/key/after-table
            -skip invalid/key/after-value
            -skip invalid/key/bare-invalid-character
            -skip invalid/key/dotted-redefine-table
            -skip invalid/key/duplicate-keys
            -skip invalid/key/duplicate
            -skip invalid/key/empty
            -skip invalid/key/escape
            -skip invalid/key/hash
            -skip invalid/key/multiline
            -skip invalid/key/newline
            -skip invalid/key/no-eol
            -skip invalid/key/open-bracket
            -skip invalid/key/partial-quoted
            -skip invalid/key/single-open-bracket
            -skip invalid/key/space
            -skip invalid/key/special-character
            -skip invalid/key/start-bracket
            -skip invalid/key/two-equals
            -skip invalid/key/two-equals2
            -skip invalid/key/two-equals3
            -skip invalid/key/without-value-1
            -skip invalid/key/without-value-2
            -skip invalid/string/bad-byte-escape
            -skip invalid/string/bad-codepoint
            -skip invalid/string/bad-concat
            -skip invalid/string/bad-escape-1
            -skip invalid/string/bad-escape-2
            -skip invalid/string/bad-multiline
            -skip invalid/string/bad-slash-escape
            -skip invalid/string/bad-uni-esc
            -skip invalid/string/basic-byte-escapes
            -skip invalid/string/basic-multiline-out-of-range-unicode-escape-1
            -skip invalid/string/basic-multiline-out-of-range-unicode-escape-2
            -skip invalid/string/basic-multiline-quotes
            -skip invalid/string/basic-multiline-unknown-escape
            -skip invalid/string/basic-out-of-range-unicode-escape-1
            -skip invalid/string/basic-out-of-range-unicode-escape-2
            -skip invalid/string/basic-unknown-escape
            -skip invalid/string/literal-multiline-quotes-1
            -skip invalid/string/literal-multiline-quotes-2
            -skip invalid/string/missing-quotes
            -skip invalid/string/multiline-bad-escape-1
            -skip invalid/string/multiline-bad-escape-2
            -skip invalid/string/multiline-bad-escape-3
            -skip invalid/string/multiline-escape-space
            -skip invalid/string/multiline-no-close-2
            -skip invalid/string/multiline-no-close
            -skip invalid/string/multiline-quotes-1
            -skip invalid/string/no-close
            -skip invalid/string/text-after-string
            -skip invalid/string/wrong-close
            -skip invalid/table/append-with-dotted-keys-1
            -skip invalid/table/append-with-dotted-keys-2
            -skip invalid/table/array-empty
            -skip invalid/table/array-implicit
            -skip invalid/table/array-missing-bracket
            -skip invalid/table/duplicate-key-dotted-table
            -skip invalid/table/duplicate-key-dotted-table2
            -skip invalid/table/duplicate-key-table
            -skip invalid/table/duplicate-table-array
            -skip invalid/table/duplicate-table-array2
            -skip invalid/table/duplicate
            -skip invalid/table/empty-implicit-table
            -skip invalid/table/empty
            -skip invalid/table/equals-sign
            -skip invalid/table/llbrace
            -skip invalid/table/nested-brackets-close
            -skip invalid/table/nested-brackets-open
            -skip invalid/table/quoted-no-close
            -skip invalid/table/redefine
            -skip invalid/table/rrbrace
            -skip invalid/table/text-after-table
            -skip invalid/table/whitespace
            -skip invalid/table/with-pound
          '

      - name: Check that Cabal file was generated
        run: git diff --exit-code '*.cabal'

      # upload coverage data
      - name: Generate coverage data
        run: stack install hpc-lcov && hpc-lcov
      - uses: codecov/codecov-action@v2
        with:
          files: lcov.info
        if: ${{ matrix.latest }}

  lint:
    runs-on: ubuntu-latest
    env:
      FOURMOLU_VERSION: '0.6.0.0'
    steps:
      - uses: actions/checkout@v2

      - name: Install fourmolu
        run: |
          curl -sSL \
            "https://github.com/fourmolu/fourmolu/releases/download/v${FOURMOLU_VERSION}/fourmolu-${FOURMOLU_VERSION}-linux-x86_64" \
            -o /usr/local/bin/fourmolu
          chmod +x /usr/local/bin/fourmolu
      - name: Run fourmolu
        run: fourmolu -m check $(git ls-files '*.hs')
