name: CI
on: push

jobs:
  build_and_test:
    strategy:
      matrix:
        stack_yaml:
          - stack-ghc-8.6.yaml
          - stack-ghc-8.8.yaml
          - stack-ghc-8.10.yaml
          - stack-ghc-9.0.yaml
          - stack-ghc-9.2.yaml
        include:
          - stack_yaml: stack.yaml
            latest: true

    name: build_and_test (${{ matrix.stack_yaml }})
    runs-on: ubuntu-latest
    env:
      STACK_YAML: ${{ matrix.stack_yaml }}

    steps:
      - uses: actions/checkout@v2

      - name: Install toml-test
        env:
          TOML_TEST_VERSION: '1.1.0'
        run: |
          curl -sSL \
            "https://github.com/BurntSushi/toml-test/releases/download/v${TOML_TEST_VERSION}/toml-test-v${TOML_TEST_VERSION}-linux-amd64.gz" \
            -o toml-test.gz
          gunzip toml-test.gz
          chmod +x toml-test
          mv toml-test /usr/local/bin/

      - uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-cache-${{ hashFiles(matrix.stack_yaml, 'package.yaml') }}
      - name: Build + test
        run: stack build --test --coverage

      # upload coverage data
      - name: Generate coverage data
        run: stack install hpc-lcov && hpc-lcov
      - uses: codecov/codecov-action@v2
        with:
          files: lcov.info
        if: ${{ matrix.latest }}

  lint:
    runs-on: ubuntu-latest
    env:
      FOURMOLU_VERSION: '0.6.0.0'
    steps:
      - uses: actions/checkout@v2

      - name: Install fourmolu
        run: |
          curl -sSL \
            "https://github.com/fourmolu/fourmolu/releases/download/v${FOURMOLU_VERSION}/fourmolu-${FOURMOLU_VERSION}-linux-x86_64" \
            -o /usr/local/bin/fourmolu
          chmod +x /usr/local/bin/fourmolu
      - name: Run fourmolu
        run: fourmolu -m check $(git ls-files '*.hs')
